#!/usr/bin/env python3
"""AT-SPI C++ 源码扫描器 — 独立版，无 at-spi-completion 依赖。

扫描 C++ 源码中的可交互控件实例，统计：
- 元素 A（所有可交互控件）
- 元素 B（已有 setObjectName + setAccessibleName 的控件）
- 覆盖率 = |B| / |A|

输出：pre_scan_gaps.yaml（gap 列表）+ pre_scan_ok.yaml（已有名称的控件）
"""
from __future__ import annotations

import argparse
import json
import logging
import multiprocessing
import os
import sys
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger("coverage_scan_cpp")

# ── libclang 初始化（完整版）───────────────────────────────────
_LIBCLANG_CANDIDATES = [
    "/usr/lib/x86_64-linux-gnu",
    "/usr/lib64",
    "/usr/lib",
    "/usr/lib/llvm-18/lib",
    "/usr/lib/llvm-17/lib",
    "/usr/lib/llvm-19/lib",
    "/usr/lib/python3/dist-packages/",
    "/usr/lib/python3.12/dist-packages/",
    "/usr/lib/python3.11/dist-packages/",
    "/usr/lib/clang/",
]

_libclang_libpath: str | None = None
for _base in _LIBCLANG_CANDIDATES:
    _p = Path(_base)
    if not _p.is_dir():
        continue
    try:
        for _f in _p.iterdir():
            if "libclang" in _f.name and _f.suffix in (".so", ".so.1"):
                _libclang_libpath = _base
                break
    except OSError:
        continue
    if _libclang_libpath:
        break

if _libclang_libpath:
    _key = "LD_LIBRARY_PATH"
    _old = os.environ.get(_key, "")
    if _libclang_libpath not in _old:
        os.environ[_key] = f"{_libclang_libpath}:{_old}" if _old else _libclang_libpath
    from clang.cindex import Config
    Config.set_library_path(_libclang_libpath)
    _LIBCLANG_READY = True
else:
    _LIBCLANG_READY = False

try:
    from clang.cindex import CursorKind, Index
    _LIBCLANG_IMPORT_OK = True
except ImportError:
    CursorKind = None  # type: ignore
    _LIBCLANG_IMPORT_OK = False

# ── Type database（继承链分类，来自 type_db.json）────────────────
_TYPE_DB_PATH = Path(__file__).resolve().parent / "type_db.json"


class TypeDatabase:
    """Loads and queries the type classification database.

    The database is generated by generate_type_db.py and contains
    inheritance-based classification for all DTK and Qt widget types.
    Falls back to hardcoded sets when the DB file is unavailable.
    """

    def __init__(self, db_path: str | Path | None = None) -> None:
        self._db: dict | None = None
        self._custom_types: dict[str, str] = {}
        self._load(db_path or _TYPE_DB_PATH)

    def _load(self, path: str | Path) -> None:
        p = Path(path)
        if p.is_file():
            try:
                import json
                with open(p) as f:
                    self._db = json.load(f)
                logger.info("Loaded type DB: %s (%d classes)", p, len(self._db.get("classes", {})))
            except Exception as e:
                logger.warning("Failed to load type DB %s: %s", p, e)
                self._db = None
        else:
            logger.warning("Type DB not found: %s — using fallback sets", p)
            self._db = None

    def _classify(self, type_name: str) -> str:
        """Classify a type name using the DB and inheritance chain."""
        base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
        if base in self._custom_types:
            return self._custom_types[base]
        if self._db is None:
            return "unknown"
        classes = self._db.get("classes", {})
        qt_roots = self._db.get("qt_roots", {})
        seen = set()
        current = base
        while current and current not in seen:
            seen.add(current)
            info = classes.get(current)
            if info:
                cat = info.get("category", "unknown")
                if cat != "unknown":
                    return cat
                bases = info.get("bases", [])
                if bases:
                    current = bases[0]
                    if "::" in current:
                        current = current.split("::")[-1]
                    continue
            if current in qt_roots.get("interactive", []):
                return "interactive"
            if current in qt_roots.get("decorative", []):
                return "decorative"
            if current in qt_roots.get("layout", []):
                return "layout"
            if current is None:
                break
            matched = False
            for cls_name, info in classes.items():
                if len(cls_name) < 4:
                    continue
                if current.endswith(cls_name):
                    cat = info.get("category", "unknown")
                    if cat != "unknown":
                        return cat
                    bases = info.get("bases", [])
                    if bases:
                        current = bases[0].split("::")[-1] if "::" in bases[0] else bases[0]
                        matched = True
                        break
                    else:
                        current = None
                        matched = True
                        break
            if not matched:
                current = None
        for ancestor in seen:
            if ancestor in qt_roots.get("interactive", []):
                return "interactive"
            if ancestor in qt_roots.get("decorative", []):
                return "decorative"
            if ancestor in qt_roots.get("layout", []):
                return "layout"
        _KNOWN_QT_INTERACTIVE = frozenset({
            "QPushButton", "QToolButton", "QCheckBox", "QRadioButton",
            "QLineEdit", "QTextEdit", "QPlainTextEdit", "QComboBox",
            "QSlider", "QSpinBox", "QDoubleSpinBox", "QScrollBar",
            "QListWidget", "QTreeWidget", "QTableWidget",
            "QListView", "QTreeView", "QTableView",
            "QTabBar", "QKeySequenceEdit",
            "QMenu", "QMenuBar",
            "QAction", "QActionGroup", "QShortcut",
            "QButtonGroup",
            "QDialogButtonBox", "QCalendarWidget", "QFontComboBox",
            "QAbstractItemView", "QAbstractScrollArea",
        })
        _KNOWN_QT_DECORATIVE = frozenset({
            "QWidget", "QMainWindow", "QDialog", "QWindow", "QFrame",
            "QLabel", "QProgressBar", "QGraphicsView",
            "QGroupBox", "QScrollArea", "QSplitter",
            "QStackedWidget", "QStatusBar", "QTabWidget", "QToolBar",
        })
        for ancestor in seen:
            if ancestor in _KNOWN_QT_INTERACTIVE:
                return "interactive"
            if ancestor in _KNOWN_QT_DECORATIVE:
                return "decorative"
        return "unknown"

    def is_ui_type(self, type_name: str) -> bool:
        return self._classify(type_name) != "unknown"

    def is_interactive(self, type_name: str) -> bool:
        return self._classify(type_name) == "interactive"

    def is_layout(self, type_name: str) -> bool:
        return self._classify(type_name) == "layout"

    def is_decorative(self, type_name: str) -> bool:
        return self._classify(type_name) == "decorative"

    def register_custom_type(self, name: str, category: str) -> None:
        self._custom_types[name] = category

    def resolve_custom_types(self, source_dir: str | Path,
                             project_includes: list[str] | None = None) -> None:
        """Scan project headers for custom widget types and classify them."""
        if not _LIBCLANG_READY:
            return
        root = Path(source_dir)
        if not root.is_dir():
            return
        all_headers = sorted(root.rglob("*.h"))
        found = 0
        for h in all_headers:
            try:
                content = h.read_text(errors="replace")
                if "class " not in content or ": public " not in content:
                    continue
                for line in content.splitlines():
                    line = line.strip()
                    if line.startswith("class ") and ": public " in line:
                        cls_name = line.split(":")[0].replace("class", "").strip()
                        if cls_name and not cls_name.startswith("Q") and not cls_name.startswith("D"):
                            base_raw = line.split(": public ")[-1].split("{")[0].strip()
                            base_raw = base_raw.split("::")[-1] if "::" in base_raw else base_raw
                            base_raw = base_raw.split("<")[0].strip()
                            cat = self._classify(base_raw)
                            if cat != "unknown" and cls_name not in self._custom_types:
                                self._custom_types[cls_name] = cat
                                found += 1
            except Exception:
                continue
        logger.info("resolve_custom_types: found %d custom types (parsed %d headers)", found, len(all_headers))


_TYPE_DB = TypeDatabase()
# ── 分类常量（从 classify.py 内联，避免跨文件依赖）─────────────
_INTERACTIVE_CLASSES: frozenset[str] = frozenset({
    "DPushButton", "DToolButton", "DIconButton", "DSwitchButton",
    "DSuggestButton", "DCommandLinkButton", "DFloatingButton",
    "DAbstractButton", "DButtonBox",
    "QPushButton", "QToolButton", "QDialogButtonBox",
    "DLineEdit", "DTextEdit", "DComboBox", "DCheckBox", "DRadioButton",
    "DSlider", "DSpinBox", "DPasswordEdit", "DSearchEdit", "DFileChooserEdit",
    "DKeySequenceEdit",
    "QLineEdit", "QTextEdit", "QComboBox", "QCheckBox", "QRadioButton",
    "QSlider", "QSpinBox", "QDoubleSpinBox", "QKeySequenceEdit",
    "DListView", "DTreeView", "DTabBar",
    "QListWidget", "QTreeWidget", "QTableWidget",
    "QListView", "QTreeView", "QTableView",
    "QTabBar", "QScrollBar",
    "QMenu", "QMenuBar", "DMenu", "DMenuItem", "DMenuBar",
    "QAction", "QActionGroup", "QShortcut", "QButtonGroup",
    "DAction",
    "QCalendarWidget",
})

_NON_WIDGET_INTERACTIVE: frozenset[str] = frozenset({
    "QAction", "QActionGroup", "QShortcut", "QButtonGroup", "DAction",
})

_DECORATIVE_CLASSES: frozenset[str] = frozenset({
    "DLabel", "DTitlebar", "DProgressBar", "DIndeterminateProgressBar",
    "DWaterProgress", "DAlertControl",
    "DHeaderLine", "DShadowLine", "DVerticalLine",
    "DArrowRectangle", "DToolTip", "DClipEffectWidget",
    "DFlyoutWidget", "DMessageBox",
    "DFloatingMessage", "DFloatingWidget", "DDrawer",
    "DSegmentedControl",
    "DGroupBox", "DScrollArea", "DSplitter",
    "DStackedWidget", "DStatusBar", "DTabWidget", "DToolBar",
    "QLabel", "QProgressBar", "QFrame", "QGraphicsView",
    "QMainWindow", "QWidget", "QDialog", "QWindow",
    "QGroupBox", "QScrollArea", "QSplitter",
    "QStackedWidget", "QStatusBar", "QTabWidget", "QToolBar",
})

_LAYOUT_CLASSES: frozenset[str] = frozenset({
    "QHBoxLayout", "QVBoxLayout", "QGridLayout", "QFormLayout",
    "QStackedLayout", "QBoxLayout",
})

_ALL_UI_CLASSES = _INTERACTIVE_CLASSES | _DECORATIVE_CLASSES | _LAYOUT_CLASSES | _NON_WIDGET_INTERACTIVE


def _is_ui_type(type_name: str) -> bool:
    base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
    if _TYPE_DB.is_ui_type(base):
        return True
    if base in _ALL_UI_CLASSES:
        return True
    for cls in _ALL_UI_CLASSES:
        if base.endswith(cls):
            return True
    return False


def _is_interactive_type(type_name: str) -> bool:
    base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
    if _TYPE_DB.is_interactive(base):
        return True
    if base in _INTERACTIVE_CLASSES:
        return True
    for cls in _INTERACTIVE_CLASSES:
        if base.endswith(cls):
            return True
    return False


def _is_non_widget_interactive(type_name: str) -> bool:
    base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
    if base in _NON_WIDGET_INTERACTIVE:
        return True
    for cls in _NON_WIDGET_INTERACTIVE:
        if base.endswith(cls):
            return True
    return False


def _is_layout_type(type_name: str) -> bool:
    base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
    if _TYPE_DB.is_layout(base):
        return True
    return base in _LAYOUT_CLASSES


def _is_decorative_type(type_name: str) -> bool:
    base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
    if _TYPE_DB.is_decorative(base):
        return True
    return base in _DECORATIVE_CLASSES


# ── 数据结构 ──────────────────────────────────────────────────
@dataclass
class WidgetInstance:
    variable: str = ""
    type_name: str = ""
    source_file: str = ""
    class_name: str = ""
    line: int = 0
    instantiation: str = ""
    has_object_name: bool = False
    has_accessible_name: bool = False
    existing_object_name: str = ""
    existing_accessible_name: str = ""
    display_text: str = ""
    role: str = ""
    context: str = ""
    is_action: bool = False
    action_owner: str = ""


@dataclass
class ScanResult:
    source_dir: str
    total_files: int = 0
    parsed_files: int = 0
    failed_files: int = 0
    widgets: list[WidgetInstance] = field(default_factory=list)
    ok_widgets: list[WidgetInstance] = field(default_factory=list)
    gap_widgets: list[WidgetInstance] = field(default_factory=list)


# ── 角色映射 ──────────────────────────────────────────────────
_TYPE_TO_ROLE: dict[str, str] = {
    "push button": "push button", "tool button": "push button",
    "check box": "check box", "radio button": "radio button",
    "combo box": "combo box", "spin box": "spin box",
    "slider": "slider", "scroll bar": "scroll bar",
    "progress bar": "progress bar",
    "line edit": "text", "text edit": "text",
    "label": "label", "menu": "menu",
    "menu item": "menu item", "menu bar": "menu bar",
    "tool bar": "tool bar", "status bar": "status bar",
    "tab": "page tab", "tab widget": "page tab list",
    "list view": "list", "tree view": "tree",
    "table view": "table",
    "scroll area": "scroll pane", "splitter": "split pane",
    "group box": "grouping", "frame": "frame",
    "stacked widget": "layered pane",
    "action": "push button", "shortcut": "accelerator label",
    "key sequence edit": "text",
}


def _map_role(type_name: str) -> str:
    base = type_name.replace(" *", "").replace("&", "").split("<")[0].strip()
    if base.startswith("D") and len(base) > 1 and base[1].isupper():
        base = base[1:]
    base_nospace = base.lower().replace(" ", "")
    for key, role in _TYPE_TO_ROLE.items():
        key_nospace = key.lower().replace(" ", "")
        if key_nospace in base_nospace:
            return role
    return ""


# ── 编译命令加载 ──────────────────────────────────────────────
def _load_compile_commands(cc_path: str) -> dict[str, list[str]] | None:
    try:
        with open(cc_path) as f:
            entries = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None
    result: dict[str, list[str]] = {}
    for entry in entries:
        file = entry.get("file", "")
        args = entry.get("arguments", [])
        if file and args:
            result[file] = args
    return result if result else None


def _get_cxx_stdlib_flags() -> list[str]:
    flags: list[str] = []
    try:
        r = subprocess.run(["g++", "-E", "-x", "c++", "-std=c++17", "-v", "/dev/null"],
                           capture_output=True, text=True, timeout=10)
        for line in r.stderr.splitlines():
            line = line.strip()
            if line.startswith("/") and ("include" in line or "include-fixed" in line):
                flags.append(f"-isystem{line}")
    except Exception:
        pass
    return flags


def _probe_qt_base() -> list[str]:
    bases: list[str] = []
    for candidate in ["/usr/include/x86_64-linux-gnu/qt6", "/usr/include/qt6",
                       "/usr/include/x86_64-linux-gnu/qt5", "/usr/include/qt5"]:
        if Path(candidate).is_dir():
            bases.append(candidate)
    return bases


def _probe_dtk_base() -> list[str]:
    bases: list[str] = []
    for candidate in ["/usr/include/x86_64-linux-gnu/dtk6", "/usr/include/dtk6",
                       "/usr/include/x86_64-linux-gnu/dtk5", "/usr/include/dtk5",
                       "/usr/include/libdtk-6", "/usr/include/libdtk-5"]:
        if Path(candidate).is_dir():
            bases.append(candidate)
    return bases


def _get_qt_dtk_include_flags() -> list[str]:
    flags: list[str] = []
    for base in _probe_qt_base():
        flags.append(f"-I{base}")
        flags.append(f"-I{base}/QtCore")
        flags.append(f"-I{base}/QtWidgets")
        flags.append(f"-I{base}/QtGui")
    for base in _probe_dtk_base():
        flags.append(f"-I{base}")
        flags.append(f"-I{base}/DWidget")
        flags.append(f"-I{base}/DCore")
    return flags


# ── 源码游标迭代 ──────────────────────────────────────────────
def _iter_source_cursors(root_cursor, source_path: str, header_path: str | None = None):
    def _walk(cursor):
        for child in cursor.get_children():
            loc = child.location
            if loc and loc.file:
                f = str(loc.file)
                if f == source_path or (header_path and f == header_path):
                    yield child
            yield from _walk(child)

    yield from _walk(root_cursor)


def _get_header_path(file_path: str) -> str | None:
    p = Path(file_path)
    for ext in [".h", ".hpp", ".hxx"]:
        hp = p.with_suffix(ext)
        if hp.is_file():
            return str(hp)
    return None


def _extract_string_literal(cursor) -> str | None:
    for child in cursor.get_children():
        if child.kind == CursorKind.STRING_LITERAL:
            return child.spelling.strip('"') if child.spelling else None
        result = _extract_string_literal(child)
        if result:
            return result
    return None


def _detect_call_in_unexposed(cursor, widgets, name_calls, all_named_vars):
    for child in cursor.get_children():
        if child.kind == CursorKind.CALL_EXPR:
            spelling = child.spelling or ""
            if spelling in ("setObjectName", "setAccessibleName", "set_Object_Name"):
                target_var = ""
                name_value = ""
                call_type = spelling
                for gc in child.get_children():
                    if gc.kind == CursorKind.MEMBER_REF_EXPR:
                        for hc in gc.get_children():
                            if hc.kind == CursorKind.DECL_REF_EXPR:
                                target_var = hc.spelling or ""
                    lit = _extract_string_literal(gc)
                    if lit:
                        name_value = lit
                if target_var and call_type:
                    all_named_vars.add(target_var)
                    if target_var in widgets:
                        if target_var not in name_calls:
                            name_calls[target_var] = set()
                        name_calls[target_var].add((call_type, name_value))


# ── 单文件扫描 ──────────────────────────────────────────────────
def _scan_one_file(file_path: str, rel_path: str, extra_args: list[str]) -> tuple:
    try:
        index = Index.create()
        tu = index.parse(file_path, args=extra_args)
    except Exception as e:
        return rel_path, [], [], set(), str(e)

    widgets: dict[str, WidgetInstance] = {}
    ok_widgets_list: list[WidgetInstance] = []
    gap_widgets_list: list[WidgetInstance] = []
    name_calls: dict[str, set[tuple[str, str]]] = {}
    all_named_vars: set[str] = set()
    class_name: str = ""
    header_path = _get_header_path(file_path)

    # Pass 1: FIELD_DECL
    for cursor in _iter_source_cursors(tu.cursor, file_path, header_path):
        try:
            if cursor.kind in (CursorKind.CLASS_DECL, CursorKind.STRUCT_DECL):
                if cursor.semantic_parent and cursor.semantic_parent.kind != CursorKind.TRANSLATION_UNIT:
                    continue
                if cursor.spelling and not cursor.spelling.startswith("__"):
                    class_name = cursor.spelling
            if cursor.kind == CursorKind.FIELD_DECL:
                type_name = cursor.type.spelling if cursor.type else ""
                var_name = cursor.spelling or ""
                if not var_name or not type_name:
                    continue
                is_ui = _is_ui_type(type_name)
                is_interactive = _is_interactive_type(type_name)
                is_layout = _is_layout_type(type_name)
                is_decorative = _is_decorative_type(type_name)
                if is_ui or is_interactive or (not is_layout and not is_decorative
                                                and _is_widget_pointer_type(type_name)):
                    if var_name not in widgets:
                        inst = WidgetInstance(
                            variable=var_name, type_name=type_name,
                            source_file=rel_path, class_name=class_name,
                            line=cursor.location.line, role=_map_role(type_name),
                        )
                        widgets[var_name] = inst
        except Exception:
            continue

    # Pass 2: CALL_EXPR
    for cursor in _iter_source_cursors(tu.cursor, file_path):
        try:
            if cursor.kind == CursorKind.CALL_EXPR:
                spelling = cursor.spelling or ""
                children = list(cursor.get_children())
                target_var = ""
                name_value = ""
                call_type = ""
                if spelling in ("setObjectName", "setAccessibleName", "set_Object_Name"):
                    call_type = spelling
                    for child in children:
                        if child.kind == CursorKind.MEMBER_REF_EXPR:
                            ref = child.referenced
                            if ref and ref.spelling in ("setObjectName", "setAccessibleName"):
                                for gc in child.get_children():
                                    if gc.kind == CursorKind.UNEXPOSED_EXPR:
                                        target_var = gc.spelling or ""
                                        break
                            else:
                                target_var = ref.spelling if ref else ""
                        lit = _extract_string_literal(child)
                        if lit:
                            name_value = lit
                elif not spelling and children:
                    member_ref = None
                    string_lit = None
                    for child in children:
                        if child.kind == CursorKind.MEMBER_REF_EXPR:
                            member_ref = child
                        elif child.kind == CursorKind.STRING_LITERAL:
                            string_lit = child
                    if member_ref:
                        lit = _extract_string_literal(cursor)
                        if lit:
                            name_value = lit

                        def _extract_target(c):
                            if c.kind == CursorKind.DECL_REF_EXPR:
                                return c.spelling or ""
                            if c.kind == CursorKind.UNEXPOSED_EXPR:
                                for gc in c.get_children():
                                    result = _extract_target(gc)
                                    if result:
                                        return result
                            return ""

                        for gc in member_ref.get_children():
                            if gc.kind == CursorKind.UNEXPOSED_EXPR:
                                target_var = _extract_target(gc)
                            elif gc.kind == CursorKind.DECL_REF_EXPR:
                                target_var = gc.spelling or ""
                            elif gc.kind == CursorKind.OVERLOADED_DECL_REF:
                                call_type = gc.spelling or ""
                        if not call_type:
                            for gc in member_ref.get_children():
                                if gc.kind == CursorKind.OVERLOADED_DECL_REF:
                                    call_type = gc.spelling or ""
                                    break
                        if target_var and not call_type:
                            call_type = "setObjectName"
                if target_var and call_type:
                    all_named_vars.add(target_var)
                    if target_var in widgets:
                        if target_var not in name_calls:
                            name_calls[target_var] = set()
                        name_calls[target_var].add((call_type, name_value))
                        if call_type == "setObjectName" and not spelling:
                            name_calls[target_var].add(("setAccessibleName", name_value))

            if cursor.kind == CursorKind.UNEXPOSED_EXPR:
                _detect_call_in_unexposed(cursor, widgets, name_calls, all_named_vars)

            if cursor.kind == CursorKind.CXX_NEW_EXPR:
                created_type = cursor.type.spelling if cursor.type else ""
                if "QAction" in created_type or "DAction" in created_type:
                    tr_text = _extract_string_literal(cursor)
                    if tr_text:
                        parent = cursor.semantic_parent
                        if parent:
                            for sibling in parent.get_children():
                                if sibling.kind == CursorKind.BINARY_OPERATOR:
                                    lhs = list(sibling.get_children())
                                    if lhs and lhs[0].kind == CursorKind.DECL_REF_EXPR:
                                        var = lhs[0].spelling or ""
                                        if var in widgets:
                                            widgets[var].display_text = tr_text
                                            widgets[var].line = cursor.location.line
        except Exception:
            continue

    # Pass 3: classify
    for var_name, inst in widgets.items():
        if var_name in name_calls:
            for call_type, name_val in name_calls[var_name]:
                if call_type == "setObjectName":
                    inst.has_object_name = True
                    inst.existing_object_name = name_val
                elif call_type == "setAccessibleName":
                    inst.has_accessible_name = True
                    inst.existing_accessible_name = name_val
        is_interactive = _is_interactive_type(inst.type_name)
        is_decorative = _is_decorative_type(inst.type_name)
        is_layout = _is_layout_type(inst.type_name)
        if is_layout:
            continue
        if is_decorative and not inst.has_object_name and not inst.has_accessible_name:
            continue
        if inst.has_object_name or inst.has_accessible_name:
            if is_interactive and not _is_non_widget_interactive(inst.type_name):
                if inst.has_object_name and inst.has_accessible_name:
                    ok_widgets_list.append(inst)
                else:
                    gap_widgets_list.append(inst)
            else:
                ok_widgets_list.append(inst)
        elif is_interactive:
            gap_widgets_list.append(inst)

    return rel_path, ok_widgets_list, gap_widgets_list, all_named_vars, None


def _worker_init(extra_args: list[str]):
    pass


def _worker_scan_batch(batch: list[tuple[str, str, list[str]]]) -> list[tuple]:
    return [_scan_one_file(*item) for item in batch]

# ── Grep 回退模式（无 libclang 时使用）─────────────────────────


def _scan_grep_fallback(src_dir: str, output_dir: str = ".") -> ScanResult:
    """Text-grep based scan: no libclang needed.

    Scans .h files for widget member declarations, .cpp files for
    setObjectName/setAccessibleName calls. Less precise than libclang
    but works without any C++ parser.
    """
    root = Path(src_dir)
    if not root.is_dir():
        logger.error("Source directory not found: %s", src_dir)
        return ScanResult(source_dir=src_dir)

    # Collect all widget member declarations from .h files
    # Pattern: "Type *variable;" or "Type variable;" where Type is in our sets
    import re
    widgets: dict[str, WidgetInstance] = {}
    class_name = ""

    # Build union of all known type names for regex
    all_types = _INTERACTIVE_CLASSES | _DECORATIVE_CLASSES | _NON_WIDGET_INTERACTIVE | _LAYOUT_CLASSES
    # Sort by length descending so longer names match first
    type_patterns = sorted(all_types, key=len, reverse=True)
    type_re = re.compile(r"(" + "|".join(re.escape(t) for t in type_patterns) + r")\s*\*?\s*(\w+)\s*[;=]")

    # Also match custom types from TypeDatabase
    custom_types = list(_TYPE_DB._custom_types.keys()) if hasattr(_TYPE_DB, '_custom_types') else []
    if custom_types:
        custom_re = re.compile(r"(" + "|".join(re.escape(t) for t in custom_types) + r")\s*\*?\s*(\w+)\s*[;=]")
    else:
        custom_re = None

    header_files = sorted(root.rglob("*.h"))
    for hf in header_files:
        if any(part in {"tests", "test", "build", ".git", "debian", "3rdparty"} for part in hf.parts):
            continue
        try:
            content = hf.read_text(errors="replace")
        except Exception:
            continue
        # Track class name
        for line in content.splitlines():
            ls = line.strip()
            if ls.startswith("class ") and "{" in ls:
                cn = ls.split("{")[0].replace("class", "").strip().split()[0] if ls.split("{")[0].replace("class", "").strip() else ""
                if cn:
                    class_name = cn
        # Find widget declarations
        for m in type_re.finditer(content):
            typ, var = m.group(1), m.group(2)
            if var and var not in widgets:
                line_no = content[:m.start()].count("\n") + 1
                rel_path = str(hf.relative_to(root))
                widgets[var] = WidgetInstance(
                    variable=var, type_name=typ + "*",
                    source_file=rel_path, class_name=class_name,
                    line=line_no, role=_map_role(typ),
                )
        if custom_re:
            for m in custom_re.finditer(content):
                typ, var = m.group(1), m.group(2)
                if var and var not in widgets:
                    line_no = content[:m.start()].count("\n") + 1
                    rel_path = str(hf.relative_to(root))
                    widgets[var] = WidgetInstance(
                        variable=var, type_name=typ + "*",
                        source_file=rel_path, class_name=class_name,
                        line=line_no, role=_map_role(typ),
                    )

    # Find setObjectName/setAccessibleName calls in .cpp files
    name_calls: dict[str, set[tuple[str, str]]] = {}
    all_named_vars: set[str] = set()
    call_re = re.compile(r"(\w+)\s*->\s*(setObjectName|setAccessibleName)\s*\(\s*\"([^\"]*)\"\s*\)")

    cpp_files = sorted(root.rglob("*.cpp"))
    for cf in cpp_files:
        if any(part in {"tests", "test", "build", ".git", "debian", "3rdparty"} for part in cf.parts):
            continue
        try:
            content = cf.read_text(errors="replace")
        except Exception:
            continue
        for m in call_re.finditer(content):
            var, call_type, name_val = m.group(1), m.group(2), m.group(3)
            all_named_vars.add(var)
            if var in widgets:
                if var not in name_calls:
                    name_calls[var] = set()
                name_calls[var].add((call_type, name_val))

    # Classify
    all_ok: list[WidgetInstance] = []
    all_gaps: list[WidgetInstance] = []
    for var_name, inst in widgets.items():
        if var_name in name_calls:
            for call_type, name_val in name_calls[var_name]:
                if call_type == "setObjectName":
                    inst.has_object_name = True
                    inst.existing_object_name = name_val
                elif call_type == "setAccessibleName":
                    inst.has_accessible_name = True
                    inst.existing_accessible_name = name_val
        is_interactive = _is_interactive_type(inst.type_name)
        is_decorative = _is_decorative_type(inst.type_name)
        is_layout = _is_layout_type(inst.type_name)
        if is_layout:
            continue
        if is_decorative and not inst.has_object_name and not inst.has_accessible_name:
            continue
        if inst.has_object_name or inst.has_accessible_name:
            if is_interactive and not _is_non_widget_interactive(inst.type_name):
                if inst.has_object_name and inst.has_accessible_name:
                    all_ok.append(inst)
                else:
                    all_gaps.append(inst)
            else:
                all_ok.append(inst)
        elif is_interactive:
            all_gaps.append(inst)

    # Cross-file merge
    still_gaps: list[WidgetInstance] = []
    for g in all_gaps:
        if g.variable in all_named_vars:
            all_ok.append(g)
        else:
            still_gaps.append(g)
    all_gaps = still_gaps

    all_ok.sort(key=lambda w: (w.source_file, w.line, w.variable))
    all_gaps.sort(key=lambda w: (w.source_file, w.line, w.variable))

    result = ScanResult(
        source_dir=src_dir, total_files=len(cpp_files) + len(header_files),
        parsed_files=len(cpp_files) + len(header_files),
        widgets=all_ok + all_gaps, ok_widgets=all_ok, gap_widgets=all_gaps,
    )
    _write_outputs(result, output_dir)
    return result


# ── 主扫描编排 ──────────────────────────────────────────────────
def scan_source(src_dir: str, build_dir: str | None = None,
                compile_commands: str | None = None,
                output_dir: str = ".", mode: str = "auto") -> ScanResult:
    """Scan C++ source for AT-SPI name coverage.

    Args:
        src_dir: Source directory.
        build_dir: Build directory (for compile_commands.json).
        compile_commands: Path to compile_commands.json.
        output_dir: Output directory.
        mode: 'auto' (try libclang, fallback to grep), 'libclang' (only libclang),
              'grep' (only text grep, no libclang).
    """
    root = Path(src_dir)
    if not root.is_dir():
        logger.error("Source directory not found: %s", src_dir)
        return ScanResult(source_dir=src_dir)

    # Determine mode
    use_libclang = mode == "libclang" or (mode == "auto" and _LIBCLANG_READY and _LIBCLANG_IMPORT_OK)
    use_grep = mode == "grep" or (mode == "auto" and not (_LIBCLANG_READY and _LIBCLANG_IMPORT_OK))

    if use_grep:
        logger.info("Using grep fallback mode (no libclang)")
        return _scan_grep_fallback(src_dir, output_dir)

    if not use_libclang:
        logger.error("No scan method available. Install libclang or use --mode grep")
        return ScanResult(source_dir=src_dir)

    # ── libclang path (original) ──
    file_flags: dict[str, list[str]] | None = None
    if compile_commands:
        file_flags = _load_compile_commands(compile_commands)
    elif build_dir:
        file_flags = _load_compile_commands(str(Path(build_dir) / "compile_commands.json"))

    extra_args = ["-x", "c++", "-std=c++17", "-fPIC"]
    extra_args.extend(_get_cxx_stdlib_flags())

    project_includes: list[str] = []
    if file_flags:
        src_str = str(root)
        seen = set()
        for _file, flags in file_flags.items():
            for f in flags:
                if f.startswith("-I") and f not in seen:
                    seen.add(f)
                    inc_path = f[2:]
                    if inc_path and (inc_path.startswith(src_str) or src_str in inc_path):
                        project_includes.append(f)

    _TYPE_DB.resolve_custom_types(src_dir, project_includes)

    extensions = {".cpp", ".cxx", ".cc"}
    _SKIP_DIRS = {"tests", "test", "autotests", "autotest",
                   "build", "Build", "builddir", "_build",
                   "cmake-build", "CMakeFiles", ".cmake",
                   "debian", ".git", "3rdparty", "thirdparty", "third_party"}
    _SKIP_PREFIXES = ("test_", "moc_", "mocs_", "ui_", "qrc_")

    all_files: list[Path] = []
    for p in root.rglob("*"):
        if p.suffix not in extensions:
            continue
        if any(part in _SKIP_DIRS for part in p.parts):
            continue
        if p.stem.startswith(_SKIP_PREFIXES):
            continue
        all_files.append(p)
    all_files.sort()

    if not all_files:
        logger.warning("No C++ source files found in %s", src_dir)
        return ScanResult(source_dir=src_dir)

    task_items: list[tuple[str, str, list[str]]] = []
    for p in all_files:
        abs_path = str(p)
        rel_path = str(p.relative_to(root))
        if file_flags and abs_path in file_flags:
            flags = file_flags[abs_path]
            extra_includes = [f for f in extra_args if f.startswith("-I") or f.startswith("-isystem")]
            for inc in extra_includes:
                if inc not in flags:
                    flags.append(inc)
        else:
            flags = extra_args
        task_items.append((abs_path, rel_path, flags))

    total = len(task_items)
    n_workers = min(os.cpu_count() or 4, 8)
    batch_size = max(1, (total + n_workers - 1) // n_workers)
    batches = [task_items[i:i + batch_size] for i in range(0, total, batch_size)]

    all_ok: list[WidgetInstance] = []
    all_gaps: list[WidgetInstance] = []
    global_named_vars: set[str] = set()
    parsed = 0
    failed = 0
    done = 0

    if n_workers > 1:
        with multiprocessing.Pool(n_workers, initializer=_worker_init, initargs=(extra_args,)) as pool:
            for batch_results in pool.imap_unordered(_worker_scan_batch, batches):
                for rel_path, ok_list, gap_list, named_vars, error in batch_results:
                    if error:
                        logger.warning("Failed to parse %s: %s", rel_path, error)
                        failed += 1
                    else:
                        parsed += 1
                    all_ok.extend(ok_list)
                    all_gaps.extend(gap_list)
                    global_named_vars.update(named_vars)
                    done += 1
    else:
        for batch in batches:
            for rel_path, ok_list, gap_list, named_vars, error in _worker_scan_batch(batch):
                if error:
                    logger.warning("Failed to parse %s: %s", rel_path, error)
                    failed += 1
                else:
                    parsed += 1
                all_ok.extend(ok_list)
                all_gaps.extend(gap_list)
                global_named_vars.update(named_vars)
                done += 1

    # Cross-file merge
    still_gaps: list[WidgetInstance] = []
    for g in all_gaps:
        if g.variable in global_named_vars:
            all_ok.append(g)
        else:
            still_gaps.append(g)
    all_gaps = still_gaps

    all_ok.sort(key=lambda w: (w.source_file, w.line, w.variable))
    all_gaps.sort(key=lambda w: (w.source_file, w.line, w.variable))

    result = ScanResult(
        source_dir=src_dir, total_files=total, parsed_files=parsed,
        failed_files=failed, widgets=all_ok + all_gaps,
        ok_widgets=all_ok, gap_widgets=all_gaps,
    )

    _write_outputs(result, output_dir)
    return result


def _widget_to_dict(w: WidgetInstance) -> dict[str, Any]:
    return {
        "variable": w.variable, "type": w.type_name,
        "source_file": w.source_file, "class_name": w.class_name,
        "line": w.line, "instantiation": w.instantiation,
        "has_object_name": w.has_object_name,
        "has_accessible_name": w.has_accessible_name,
        "existing_object_name": w.existing_object_name,
        "existing_accessible_name": w.existing_accessible_name,
        "display_text": w.display_text, "role": w.role,
        "context": w.context, "is_action": w.is_action,
        "action_owner": w.action_owner,
    }


def _write_outputs(result: ScanResult, output_dir: str) -> None:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # pre_scan_gaps.yaml
    gaps_data = {
        "version": "1.0",
        "source_dir": result.source_dir,
        "total_files": result.total_files,
        "parsed_files": result.parsed_files,
        "failed_files": result.failed_files,
        "gaps": [_widget_to_dict(w) for w in result.gap_widgets],
    }
    gaps_path = out / "pre_scan_gaps.yaml"
    import yaml
    with open(gaps_path, "w", encoding="utf-8") as f:
        yaml.dump(gaps_data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    logger.info("Written %s (%d gaps)", gaps_path, len(result.gap_widgets))

    # pre_scan_ok.yaml
    ok_data = {
        "version": "1.0",
        "source_dir": result.source_dir,
        "widgets": [_widget_to_dict(w) for w in result.ok_widgets],
    }
    ok_path = out / "pre_scan_ok.yaml"
    with open(ok_path, "w", encoding="utf-8") as f:
        yaml.dump(ok_data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    logger.info("Written %s (%d ok)", ok_path, len(result.ok_widgets))

    # coverage summary
    total = len(result.widgets)
    ok_count = len(result.ok_widgets)
    gap_count = len(result.gap_widgets)
    coverage = (ok_count / total * 100) if total else 0.0
    logger.info("Coverage: %d/%d = %.1f%% (%d gaps)", ok_count, total, coverage, gap_count)


# ── CLI ──────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="AT-SPI C++ coverage scanner (standalone)")
    parser.add_argument("--src", required=True, help="Source directory")
    parser.add_argument("--build", help="Build directory (for compile_commands.json)")
    parser.add_argument("--compile-commands", help="Path to compile_commands.json")
    parser.add_argument("--output", "-o", default=".", help="Output directory")
    parser.add_argument("--mode", default="auto", choices=["auto", "libclang", "grep"],
                        help="Scan mode: auto (try libclang, fallback grep), libclang (only), grep (text only)")
    args = parser.parse_args()

    result = scan_source(
        src_dir=args.src, build_dir=args.build,
        compile_commands=args.compile_commands, output_dir=args.output,
        mode=args.mode,
    )
    return 0 if result.parsed_files > 0 else 1


if __name__ == "__main__":
    sys.exit(main())